var MENU_ICON_LIST = [
    { text: "(No icon)", value: "" },
    { text: "Edit", value: "/Content/images/grid-edit.png" },
    { text: "View", value: "/Content/images/grid-view.png" },
    { text: "Remove", value: "/Content/images/grid-delete.png" },
    { text: "Add", value: "/Content/images/icon-menu/menu-add.png" },
    { text: "Delete", value: "/Content/images/icon-menu/menu-delete.png" },
    { text: "Save", value: "/Content/images/icon-menu/menu-save.png" },
    { text: "Cancel", value: "/Content/images/icon-menu/menu-cancel.png" },
    { text: "Approve", value: "/Content/images/icon-menu/menu-approve.png" },
    { text: "Export", value: "/Content/images/icon-menu/menu-export.png" },
    { text: "Browse", value: "/Content/images/icon-menu/menu-browse.png" },
    { text: "Auto Assign", value: "/Content/images/icon-menu/menu-auto-assign.png" },
    { text: "De-active", value: "/Content/images/icon-menu/menu-deactive.png" }
];

// Bootstrap Glyphicon Icons List
var BOOTSTRAP_GLYPHICON_LIST = [
    { class: "glyphicon glyphicon-asterisk", description: "Asterisk" },
    { class: "glyphicon glyphicon-plus", description: "Plus" },
    { class: "glyphicon glyphicon-minus", description: "Minus" },
    { class: "glyphicon glyphicon-euro", description: "Euro" },
    { class: "glyphicon glyphicon-cloud", description: "Cloud" },
    { class: "glyphicon glyphicon-envelope", description: "Envelope" },
    { class: "glyphicon glyphicon-pencil", description: "Pencil" },
    { class: "glyphicon glyphicon-glass", description: "Glass" },
    { class: "glyphicon glyphicon-music", description: "Music" },
    { class: "glyphicon glyphicon-search", description: "Search" },
    { class: "glyphicon glyphicon-heart", description: "Heart" },
    { class: "glyphicon glyphicon-star", description: "Star" },
    { class: "glyphicon glyphicon-star-empty", description: "Star Empty" },
    { class: "glyphicon glyphicon-user", description: "User" },
    { class: "glyphicon glyphicon-film", description: "Film" },
    { class: "glyphicon glyphicon-th-large", description: "Th Large" },
    { class: "glyphicon glyphicon-th", description: "Th" },
    { class: "glyphicon glyphicon-th-list", description: "Th List" },
    { class: "glyphicon glyphicon-ok", description: "Ok" },
    { class: "glyphicon glyphicon-remove", description: "Remove" },
    { class: "glyphicon glyphicon-zoom-in", description: "Zoom In" },
    { class: "glyphicon glyphicon-zoom-out", description: "Zoom Out" },
    { class: "glyphicon glyphicon-off", description: "Off" },
    { class: "glyphicon glyphicon-signal", description: "Signal" },
    { class: "glyphicon glyphicon-cog", description: "Cog" },
    { class: "glyphicon glyphicon-trash", description: "Trash" },
    { class: "glyphicon glyphicon-home", description: "Home" },
    { class: "glyphicon glyphicon-file", description: "File" },
    { class: "glyphicon glyphicon-time", description: "Time" },
    { class: "glyphicon glyphicon-road", description: "Road" },
    { class: "glyphicon glyphicon-download-alt", description: "Download Alt" },
    { class: "glyphicon glyphicon-download", description: "Download" },
    { class: "glyphicon glyphicon-upload", description: "Upload" },
    { class: "glyphicon glyphicon-inbox", description: "Inbox" },
    { class: "glyphicon glyphicon-play-circle", description: "Play Circle" },
    { class: "glyphicon glyphicon-repeat", description: "Repeat" },
    { class: "glyphicon glyphicon-refresh", description: "Refresh" },
    { class: "glyphicon glyphicon-list-alt", description: "List Alt" },
    { class: "glyphicon glyphicon-lock", description: "Lock" },
    { class: "glyphicon glyphicon-flag", description: "Flag" },
    { class: "glyphicon glyphicon-headphones", description: "Headphones" },
    { class: "glyphicon glyphicon-volume-off", description: "Volume Off" },
    { class: "glyphicon glyphicon-volume-down", description: "Volume Down" },
    { class: "glyphicon glyphicon-volume-up", description: "Volume Up" },
    { class: "glyphicon glyphicon-qrcode", description: "Qrcode" },
    { class: "glyphicon glyphicon-barcode", description: "Barcode" },
    { class: "glyphicon glyphicon-tag", description: "Tag" },
    { class: "glyphicon glyphicon-tags", description: "Tags" },
    { class: "glyphicon glyphicon-book", description: "Book" },
    { class: "glyphicon glyphicon-bookmark", description: "Bookmark" },
    { class: "glyphicon glyphicon-print", description: "Print" },
    { class: "glyphicon glyphicon-camera", description: "Camera" },
    { class: "glyphicon glyphicon-font", description: "Font" },
    { class: "glyphicon glyphicon-bold", description: "Bold" },
    { class: "glyphicon glyphicon-italic", description: "Italic" },
    { class: "glyphicon glyphicon-text-height", description: "Text Height" },
    { class: "glyphicon glyphicon-text-width", description: "Text Width" },
    { class: "glyphicon glyphicon-align-left", description: "Align Left" },
    { class: "glyphicon glyphicon-align-center", description: "Align Center" },
    { class: "glyphicon glyphicon-align-right", description: "Align Right" },
    { class: "glyphicon glyphicon-align-justify", description: "Align Justify" },
    { class: "glyphicon glyphicon-list", description: "List" },
    { class: "glyphicon glyphicon-indent-left", description: "Indent Left" },
    { class: "glyphicon glyphicon-indent-right", description: "Indent Right" },
    { class: "glyphicon glyphicon-facetime-video", description: "Facetime Video" },
    { class: "glyphicon glyphicon-picture", description: "Picture" },
    { class: "glyphicon glyphicon-map-marker", description: "Map Marker" },
    { class: "glyphicon glyphicon-adjust", description: "Adjust" },
    { class: "glyphicon glyphicon-tint", description: "Tint" },
    { class: "glyphicon glyphicon-edit", description: "Edit" },
    { class: "glyphicon glyphicon-share", description: "Share" },
    { class: "glyphicon glyphicon-check", description: "Check" },
    { class: "glyphicon glyphicon-move", description: "Move" },
    { class: "glyphicon glyphicon-step-backward", description: "Step Backward" },
    { class: "glyphicon glyphicon-fast-backward", description: "Fast Backward" },
    { class: "glyphicon glyphicon-backward", description: "Backward" },
    { class: "glyphicon glyphicon-play", description: "Play" },
    { class: "glyphicon glyphicon-pause", description: "Pause" },
    { class: "glyphicon glyphicon-stop", description: "Stop" },
    { class: "glyphicon glyphicon-forward", description: "Forward" },
    { class: "glyphicon glyphicon-fast-forward", description: "Fast Forward" },
    { class: "glyphicon glyphicon-step-forward", description: "Step Forward" },
    { class: "glyphicon glyphicon-eject", description: "Eject" },
    { class: "glyphicon glyphicon-chevron-left", description: "Chevron Left" },
    { class: "glyphicon glyphicon-chevron-right", description: "Chevron Right" },
    { class: "glyphicon glyphicon-plus-sign", description: "Plus Sign" },
    { class: "glyphicon glyphicon-minus-sign", description: "Minus Sign" },
    { class: "glyphicon glyphicon-remove-sign", description: "Remove Sign" },
    { class: "glyphicon glyphicon-ok-sign", description: "Ok Sign" },
    { class: "glyphicon glyphicon-question-sign", description: "Question Sign" },
    { class: "glyphicon glyphicon-info-sign", description: "Info Sign" },
    { class: "glyphicon glyphicon-screenshot", description: "Screenshot" },
    { class: "glyphicon glyphicon-remove-circle", description: "Remove Circle" },
    { class: "glyphicon glyphicon-ok-circle", description: "Ok Circle" },
    { class: "glyphicon glyphicon-ban-circle", description: "Ban Circle" },
    { class: "glyphicon glyphicon-arrow-left", description: "Arrow Left" },
    { class: "glyphicon glyphicon-arrow-right", description: "Arrow Right" },
    { class: "glyphicon glyphicon-arrow-up", description: "Arrow Up" },
    { class: "glyphicon glyphicon-arrow-down", description: "Arrow Down" },
    { class: "glyphicon glyphicon-share-alt", description: "Share Alt" },
    { class: "glyphicon glyphicon-resize-full", description: "Resize Full" },
    { class: "glyphicon glyphicon-resize-small", description: "Resize Small" },
    { class: "glyphicon glyphicon-exclamation-sign", description: "Exclamation Sign" },
    { class: "glyphicon glyphicon-gift", description: "Gift" },
    { class: "glyphicon glyphicon-leaf", description: "Leaf" },
    { class: "glyphicon glyphicon-fire", description: "Fire" },
    { class: "glyphicon glyphicon-eye-open", description: "Eye Open" },
    { class: "glyphicon glyphicon-eye-close", description: "Eye Close" },
    { class: "glyphicon glyphicon-warning-sign", description: "Warning Sign" },
    { class: "glyphicon glyphicon-plane", description: "Plane" },
    { class: "glyphicon glyphicon-calendar", description: "Calendar" },
    { class: "glyphicon glyphicon-random", description: "Random" },
    { class: "glyphicon glyphicon-comment", description: "Comment" },
    { class: "glyphicon glyphicon-magnet", description: "Magnet" },
    { class: "glyphicon glyphicon-chevron-up", description: "Chevron Up" },
    { class: "glyphicon glyphicon-chevron-down", description: "Chevron Down" },
    { class: "glyphicon glyphicon-retweet", description: "Retweet" },
    { class: "glyphicon glyphicon-shopping-cart", description: "Shopping Cart" },
    { class: "glyphicon glyphicon-folder-close", description: "Folder Close" },
    { class: "glyphicon glyphicon-folder-open", description: "Folder Open" },
    { class: "glyphicon glyphicon-resize-vertical", description: "Resize Vertical" },
    { class: "glyphicon glyphicon-resize-horizontal", description: "Resize Horizontal" },
    { class: "glyphicon glyphicon-hdd", description: "Hdd" },
    { class: "glyphicon glyphicon-bullhorn", description: "Bullhorn" },
    { class: "glyphicon glyphicon-bell", description: "Bell" },
    { class: "glyphicon glyphicon-certificate", description: "Certificate" },
    { class: "glyphicon glyphicon-thumbs-up", description: "Thumbs Up" },
    { class: "glyphicon glyphicon-thumbs-down", description: "Thumbs Down" },
    { class: "glyphicon glyphicon-hand-right", description: "Hand Right" },
    { class: "glyphicon glyphicon-hand-left", description: "Hand Left" },
    { class: "glyphicon glyphicon-hand-up", description: "Hand Up" },
    { class: "glyphicon glyphicon-hand-down", description: "Hand Down" },
    { class: "glyphicon glyphicon-circle-arrow-right", description: "Circle Arrow Right" },
    { class: "glyphicon glyphicon-circle-arrow-left", description: "Circle Arrow Left" },
    { class: "glyphicon glyphicon-circle-arrow-up", description: "Circle Arrow Up" },
    { class: "glyphicon glyphicon-circle-arrow-down", description: "Circle Arrow Down" },
    { class: "glyphicon glyphicon-globe", description: "Globe" },
    { class: "glyphicon glyphicon-wrench", description: "Wrench" },
    { class: "glyphicon glyphicon-tasks", description: "Tasks" },
    { class: "glyphicon glyphicon-filter", description: "Filter" },
    { class: "glyphicon glyphicon-briefcase", description: "Briefcase" },
    { class: "glyphicon glyphicon-fullscreen", description: "Fullscreen" },
    { class: "glyphicon glyphicon-dashboard", description: "Dashboard" },
    { class: "glyphicon glyphicon-paperclip", description: "Paperclip" },
    { class: "glyphicon glyphicon-heart-empty", description: "Heart Empty" },
    { class: "glyphicon glyphicon-link", description: "Link" },
    { class: "glyphicon glyphicon-phone", description: "Phone" },
    { class: "glyphicon glyphicon-pushpin", description: "Pushpin" },
    { class: "glyphicon glyphicon-usd", description: "Usd" },
    { class: "glyphicon glyphicon-gbp", description: "Gbp" },
    { class: "glyphicon glyphicon-sort", description: "Sort" },
    { class: "glyphicon glyphicon-sort-by-alphabet", description: "Sort By Alphabet" },
    { class: "glyphicon glyphicon-sort-by-alphabet-alt", description: "Sort By Alphabet Alt" },
    { class: "glyphicon glyphicon-sort-by-order", description: "Sort By Order" },
    { class: "glyphicon glyphicon-sort-by-order-alt", description: "Sort By Order Alt" },
    { class: "glyphicon glyphicon-sort-by-attributes", description: "Sort By Attributes" },
    { class: "glyphicon glyphicon-sort-by-attributes-alt", description: "Sort By Attributes Alt" },
    { class: "glyphicon glyphicon-unchecked", description: "Unchecked" },
    { class: "glyphicon glyphicon-expand", description: "Expand" },
    { class: "glyphicon glyphicon-collapse-down", description: "Collapse Down" },
    { class: "glyphicon glyphicon-collapse-up", description: "Collapse Up" },
    { class: "glyphicon glyphicon-log-in", description: "Log In" },
    { class: "glyphicon glyphicon-flash", description: "Flash" },
    { class: "glyphicon glyphicon-log-out", description: "Log Out" },
    { class: "glyphicon glyphicon-new-window", description: "New Window" },
    { class: "glyphicon glyphicon-record", description: "Record" },
    { class: "glyphicon glyphicon-save", description: "Save" },
    { class: "glyphicon glyphicon-open", description: "Open" },
    { class: "glyphicon glyphicon-saved", description: "Saved" },
    { class: "glyphicon glyphicon-import", description: "Import" },
    { class: "glyphicon glyphicon-export", description: "Export" },
    { class: "glyphicon glyphicon-send", description: "Send" },
    { class: "glyphicon glyphicon-floppy-disk", description: "Floppy Disk" },
    { class: "glyphicon glyphicon-floppy-saved", description: "Floppy Saved" },
    { class: "glyphicon glyphicon-floppy-remove", description: "Floppy Remove" },
    { class: "glyphicon glyphicon-floppy-save", description: "Floppy Save" },
    { class: "glyphicon glyphicon-floppy-open", description: "Floppy Open" },
    { class: "glyphicon glyphicon-credit-card", description: "Credit Card" },
    { class: "glyphicon glyphicon-transfer", description: "Transfer" },
    { class: "glyphicon glyphicon-cutlery", description: "Cutlery" },
    { class: "glyphicon glyphicon-header", description: "Header" },
    { class: "glyphicon glyphicon-compressed", description: "Compressed" },
    { class: "glyphicon glyphicon-earphone", description: "Earphone" },
    { class: "glyphicon glyphicon-phone-alt", description: "Phone Alt" },
    { class: "glyphicon glyphicon-tower", description: "Tower" },
    { class: "glyphicon glyphicon-stats", description: "Stats" },
    { class: "glyphicon glyphicon-sd-video", description: "Sd Video" },
    { class: "glyphicon glyphicon-hd-video", description: "Hd Video" },
    { class: "glyphicon glyphicon-subtitles", description: "Subtitles" },
    { class: "glyphicon glyphicon-sound-stereo", description: "Sound Stereo" },
    { class: "glyphicon glyphicon-sound-dolby", description: "Sound Dolby" },
    { class: "glyphicon glyphicon-sound-5-1", description: "Sound 5 1" },
    { class: "glyphicon glyphicon-sound-6-1", description: "Sound 6 1" },
    { class: "glyphicon glyphicon-sound-7-1", description: "Sound 7 1" },
    { class: "glyphicon glyphicon-copyright-mark", description: "Copyright Mark" },
    { class: "glyphicon glyphicon-registration-mark", description: "Registration Mark" },
    { class: "glyphicon glyphicon-cloud-download", description: "Cloud Download" },
    { class: "glyphicon glyphicon-cloud-upload", description: "Cloud Upload" },
    { class: "glyphicon glyphicon-tree-conifer", description: "Tree Conifer" },
    { class: "glyphicon glyphicon-tree-deciduous", description: "Tree Deciduous" },
    { class: "glyphicon glyphicon-cd", description: "Cd" },
    { class: "glyphicon glyphicon-save-file", description: "Save File" },
    { class: "glyphicon glyphicon-open-file", description: "Open File" },
    { class: "glyphicon glyphicon-level-up", description: "Level Up" },
    { class: "glyphicon glyphicon-copy", description: "Copy" },
    { class: "glyphicon glyphicon-paste", description: "Paste" },
    { class: "glyphicon glyphicon-alert", description: "Alert" },
    { class: "glyphicon glyphicon-equalizer", description: "Equalizer" },
    { class: "glyphicon glyphicon-king", description: "King" },
    { class: "glyphicon glyphicon-queen", description: "Queen" },
    { class: "glyphicon glyphicon-pawn", description: "Pawn" },
    { class: "glyphicon glyphicon-bishop", description: "Bishop" },
    { class: "glyphicon glyphicon-knight", description: "Knight" },
    { class: "glyphicon glyphicon-baby-formula", description: "Baby Formula" },
    { class: "glyphicon glyphicon-tent", description: "Tent" },
    { class: "glyphicon glyphicon-blackboard", description: "Blackboard" },
    { class: "glyphicon glyphicon-bed", description: "Bed" },
    { class: "glyphicon glyphicon-apple", description: "Apple" },
    { class: "glyphicon glyphicon-erase", description: "Erase" },
    { class: "glyphicon glyphicon-hourglass", description: "Hourglass" },
    { class: "glyphicon glyphicon-lamp", description: "Lamp" },
    { class: "glyphicon glyphicon-duplicate", description: "Duplicate" },
    { class: "glyphicon glyphicon-piggy-bank", description: "Piggy Bank" },
    { class: "glyphicon glyphicon-scissors", description: "Scissors" },
    { class: "glyphicon glyphicon-bitcoin", description: "Bitcoin" },
    { class: "glyphicon glyphicon-yen", description: "Yen" },
    { class: "glyphicon glyphicon-ruble", description: "Ruble" },
    { class: "glyphicon glyphicon-scale", description: "Scale" },
    { class: "glyphicon glyphicon-ice-lolly", description: "Ice Lolly" },
    { class: "glyphicon glyphicon-ice-lolly-tasted", description: "Ice Lolly Tasted" },
    { class: "glyphicon glyphicon-education", description: "Education" },
    { class: "glyphicon glyphicon-option-horizontal", description: "Option Horizontal" },
    { class: "glyphicon glyphicon-option-vertical", description: "Option Vertical" },
    { class: "glyphicon glyphicon-menu-hamburger", description: "Menu Hamburger" },
    { class: "glyphicon glyphicon-modal-window", description: "Modal Window" },
    { class: "glyphicon glyphicon-oil", description: "Oil" },
    { class: "glyphicon glyphicon-grain", description: "Grain" },
    { class: "glyphicon glyphicon-sunglasses", description: "Sunglasses" },
    { class: "glyphicon glyphicon-text-size", description: "Text Size" },
    { class: "glyphicon glyphicon-text-color", description: "Text Color" },
    { class: "glyphicon glyphicon-text-background", description: "Text Background" },
    { class: "glyphicon glyphicon-object-align-top", description: "Object Align Top" },
    { class: "glyphicon glyphicon-object-align-bottom", description: "Object Align Bottom" },
    { class: "glyphicon glyphicon-object-align-horizontal", description: "Object Align Horizontal" },
    { class: "glyphicon glyphicon-object-align-left", description: "Object Align Left" },
    { class: "glyphicon glyphicon-object-align-vertical", description: "Object Align Vertical" },
    { class: "glyphicon glyphicon-object-align-right", description: "Object Align Right" },
    { class: "glyphicon glyphicon-triangle-right", description: "Triangle Right" },
    { class: "glyphicon glyphicon-triangle-left", description: "Triangle Left" },
    { class: "glyphicon glyphicon-triangle-bottom", description: "Triangle Bottom" },
    { class: "glyphicon glyphicon-triangle-top", description: "Triangle Top" },
    { class: "glyphicon glyphicon-console", description: "Console" },
    { class: "glyphicon glyphicon-superscript", description: "Superscript" },
    { class: "glyphicon glyphicon-subscript", description: "Subscript" },
    { class: "glyphicon glyphicon-menu-left", description: "Menu Left" },
    { class: "glyphicon glyphicon-menu-right", description: "Menu Right" },
    { class: "glyphicon glyphicon-menu-down", description: "Menu Down" },
    { class: "glyphicon glyphicon-menu-up", description: "Menu Up" }
];