//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
// </auto-generated>
//------------------------------------------------------------------------------

namespace UiBuilderFull.Admin
{
	public partial class AccessDenied
	{
		protected global::System.Web.UI.HtmlControls.HtmlForm form1;
		protected global::System.Web.UI.WebControls.HyperLink lnkHome;
	}
}
