//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
// </auto-generated>
//------------------------------------------------------------------------------

namespace BADesign.Pages
{
    public partial class AppSettings
    {
        protected global::System.Web.UI.HtmlControls.HtmlForm form1;
    }
}
