//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
// </auto-generated>
//------------------------------------------------------------------------------

namespace BADesign.Pages
{
    public partial class AuditLog
    {
        protected global::System.Web.UI.HtmlControls.HtmlForm form1;
        protected global::System.Web.UI.ScriptManager sm1;
        protected global::BADesign.BaSidebar ucBaSidebar;
        protected global::BADesign.BaTopBar ucBaTopBar;
    }
}
