//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated. 
// </auto-generated>
//------------------------------------------------------------------------------

namespace BADesign.Pages
{


	public partial class HomeRole
	{

		/// <summary>
		/// form1 control.
		/// </summary>
		/// <remarks>
		/// Auto-generated field.
		/// To modify move field declaration from designer file to code-behind file.
		/// </remarks>
		protected global::System.Web.UI.HtmlControls.HtmlForm form1;

		protected global::System.Web.UI.ScriptManager sm1;
		protected global::System.Web.UI.WebControls.HyperLink lnkNavUIBuilder;
		protected global::System.Web.UI.WebControls.HyperLink lnkNavDatabaseSearch;
		protected global::System.Web.UI.WebControls.PlaceHolder phNavEncryptDecrypt;
		protected global::System.Web.UI.WebControls.HyperLink lnkNavEncryptDecrypt;
		protected global::System.Web.UI.WebControls.Literal litPageTitle;
		protected global::System.Web.UI.WebControls.Literal litUserInitial;
		protected global::System.Web.UI.WebControls.Literal litUserName;
		protected global::System.Web.UI.WebControls.Literal litRoleBadge;
		protected global::System.Web.UI.WebControls.Literal litWelcomeTitle;
		protected global::System.Web.UI.WebControls.Literal litWelcomeDesc;
		protected global::System.Web.UI.WebControls.HyperLink lnkFeatureUIBuilder;
		protected global::System.Web.UI.WebControls.HyperLink lnkFeatureDbSearch;
		protected global::System.Web.UI.WebControls.PlaceHolder phFeatureEncryptDecrypt;
		protected global::System.Web.UI.WebControls.HyperLink lnkFeatureEncryptDecrypt;
		protected global::System.Web.UI.WebControls.PlaceHolder phNoFeatures;
		protected global::System.Web.UI.WebControls.PlaceHolder phNavSuperAdmin;
		protected global::System.Web.UI.WebControls.HyperLink lnkNavUserManagement;
		protected global::System.Web.UI.WebControls.HyperLink lnkNavRolePermission;
		protected global::System.Web.UI.WebControls.HyperLink lnkNavLeaveManager;
		protected global::System.Web.UI.WebControls.PlaceHolder phNavPgpTool;
		protected global::System.Web.UI.WebControls.HyperLink lnkNavPgpTool;
		protected global::System.Web.UI.WebControls.PlaceHolder phSuperAdminCards;
		protected global::System.Web.UI.WebControls.HyperLink lnkFeatureUserManagement;
		protected global::System.Web.UI.WebControls.HyperLink lnkFeatureRolePermission;
		protected global::System.Web.UI.WebControls.PlaceHolder phFeaturePgpTool;
		protected global::System.Web.UI.WebControls.HyperLink lnkFeaturePgpTool;
		protected global::System.Web.UI.WebControls.HyperLink lnkFeatureLeaveManager;
	}
}
