//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated. 
// </auto-generated>
//------------------------------------------------------------------------------

namespace UiBuilderFull.Admin
{


	public partial class RolePermission
	{

		/// <summary>
		/// form1 control.
		/// </summary>
		protected global::System.Web.UI.HtmlControls.HtmlForm form1;

		/// <summary>
		/// ucBaSidebar control.
		/// </summary>
		protected global::BADesign.BaSidebar ucBaSidebar;

		/// <summary>
		/// ucBaTopBar control.
		/// </summary>
		protected global::BADesign.BaTopBar ucBaTopBar;
	}
}
