-- ============================================================
-- GetEmployeeForeignKeyList.sql
-- SCRIPT DONG: Chay tren BAT KY database nao (du an nao),
-- tra ra 1 script DELETE hoan chinh. Ban copy toan bo ket qua
-- sang file moi, dien ma nhan vien (LocalEmployeeID) vao roi chay.
-- ============================================================
-- Cach dung:
-- 1. Mo ket noi den database du an (TCA, ICA, ...)
-- 2. Chay script nay (F5)
-- 3. Ket qua la NHIEU DONG (moi dong script la 1 row). Chon CA COT [Line]: click o dau cot, Shift+Click o cuoi -> Ctrl+C
-- 4. Paste vao file .sql moi, sua dong LocalEmployeeID IN ('...')
-- 5. Chay file do de xoa nhan vien
-- Luu y: Script sinh ra chi dung ky tu ASCII de "Results to File" (Ctrl+Shift+F) khong bi mat ky tu.
-- ============================================================

SET NOCOUNT ON;

-- Neu du an dung bang khac (vd Employees) thi sua dong duoi
DECLARE @EmployeeTable SYSNAME = N'Staffing_Employees';
DECLARE @EmployeeTableID INT = OBJECT_ID(N'dbo.' + @EmployeeTable);
DECLARE @Script NVARCHAR(MAX) = N'';

IF @EmployeeTableID IS NULL
BEGIN
    RAISERROR(N'Khong tim thay bang: dbo.%s. Kiem tra ten bang Employee cua du an.', 16, 1, @EmployeeTable);
    RETURN;
END

-- Danh sach bang script se XOA (de Step 2b chi kiem tra FK tham chieu cac bang nay -> nhanh hon)
DECLARE @TablesInsert NVARCHAR(MAX) = N'';
;WITH TablesWeDelete AS (
    SELECT DISTINCT OBJECT_SCHEMA_NAME(fk3.parent_object_id) AS Sn, OBJECT_NAME(fk3.parent_object_id) AS Tn
    FROM sys.foreign_keys AS fk1
    INNER JOIN sys.foreign_key_columns AS fkc1 ON fk1.object_id = fkc1.constraint_object_id AND fk1.referenced_object_id = @EmployeeTableID
    INNER JOIN sys.foreign_keys AS fk2 ON fk2.referenced_object_id = fk1.parent_object_id
    INNER JOIN sys.foreign_key_columns AS fkc2 ON fk2.object_id = fkc2.constraint_object_id
    INNER JOIN sys.foreign_keys AS fk3 ON fk3.referenced_object_id = fk2.parent_object_id
    INNER JOIN sys.foreign_key_columns AS fkc3 ON fk3.object_id = fkc3.constraint_object_id
    WHERE fk3.parent_object_id <> @EmployeeTableID
    UNION
    SELECT DISTINCT OBJECT_SCHEMA_NAME(fk2.parent_object_id), OBJECT_NAME(fk2.parent_object_id)
    FROM sys.foreign_keys AS fk1
    INNER JOIN sys.foreign_key_columns AS fkc1 ON fk1.object_id = fkc1.constraint_object_id AND fk1.referenced_object_id = @EmployeeTableID
    INNER JOIN sys.foreign_keys AS fk2 ON fk2.referenced_object_id = fk1.parent_object_id
    INNER JOIN sys.foreign_key_columns AS fkc2 ON fk2.object_id = fkc2.constraint_object_id
    WHERE fk2.parent_object_id <> @EmployeeTableID
    UNION
    SELECT DISTINCT OBJECT_SCHEMA_NAME(fk.parent_object_id), OBJECT_NAME(fk.parent_object_id)
    FROM sys.foreign_keys AS fk
    INNER JOIN sys.foreign_key_columns AS fkc ON fk.object_id = fkc.constraint_object_id
    WHERE fk.referenced_object_id = @EmployeeTableID
    UNION
    SELECT DISTINCT OBJECT_SCHEMA_NAME(fk.parent_object_id), OBJECT_NAME(fk.parent_object_id)
    FROM sys.foreign_keys fk
    INNER JOIN sys.foreign_key_columns fkc ON fk.object_id = fkc.constraint_object_id
    WHERE (fk.name LIKE N'FK_Security_GroupUsers_Security_Users%' OR (OBJECT_NAME(fk.parent_object_id) = N'Security_GroupUsers' AND OBJECT_NAME(fk.referenced_object_id) = N'Security_Users'))
    UNION
    SELECT OBJECT_SCHEMA_NAME(@EmployeeTableID), OBJECT_NAME(@EmployeeTableID)
)
SELECT @TablesInsert = (SELECT N'(N''' + REPLACE(REPLACE(Sn, N'''', N''''''), N'\', N'\\') + N''',N''' + REPLACE(REPLACE(Tn, N'''', N''''''), N'\', N'\\') + N'''),' FROM TablesWeDelete FOR XML PATH(''), TYPE).value(N'.', N'NVARCHAR(MAX)');
SET @TablesInsert = CASE WHEN LEN(ISNULL(@TablesInsert,N'')) = 0 THEN N'(N''dbo'',N''' + REPLACE(@EmployeeTable, N'''', N'''''') + N''')' ELSE LEFT(@TablesInsert, LEN(@TablesInsert)-1) END;

-- Khoi tao script: header (moi dong tach bang CRLF de copy/paste dung)
DECLARE @CRLF NCHAR(2) = NCHAR(13) + NCHAR(10);
SET @Script = N'/* Generated by GetEmployeeForeignKeyList.sql - DB: ' + DB_NAME() + N'. Edit LocalEmployeeID IN (''...'') below then run. */' + @CRLF
+ N'' + @CRLF
+ N'SET NOCOUNT ON;' + @CRLF
+ N'SET XACT_ABORT ON;' + @CRLF
+ N'' + @CRLF
+ N'BEGIN TRY' + @CRLF
+ N'    BEGIN TRANSACTION;' + @CRLF
+ N'' + @CRLF
+ N'    EXEC sp_MSforeachtable ''ALTER TABLE ? NOCHECK CONSTRAINT ALL'';' + @CRLF
+ N'    EXEC sp_MSforeachtable ''ALTER TABLE ? DISABLE TRIGGER ALL'';' + @CRLF
+ N'' + @CRLF
+ N'    DECLARE @valEmployeeID BIGINT;' + @CRLF
+ N'    DECLARE @_Cs SYSNAME, @_Ct SYSNAME, @_Cc SYSNAME, @_Rs SYSNAME, @_Rt SYSNAME, @_Rk SYSNAME, @_Sql NVARCHAR(1000), @_Orphan INT, @_i INT, @_max INT;' + @CRLF
+ N'    DECLARE mycur CURSOR FOR SELECT se.ID FROM dbo.' + QUOTENAME(@EmployeeTable) + N' AS se WHERE se.LocalEmployeeID IN (''__NHAP_MA_NHAN_VIEN_VAO_DAY__'');' + @CRLF
+ N'    IF OBJECT_ID(''tempdb..#TablesWeDeleteFrom'') IS NOT NULL DROP TABLE #TablesWeDeleteFrom;' + @CRLF
+ N'    CREATE TABLE #TablesWeDeleteFrom (SchemaName SYSNAME, TableName SYSNAME);' + @CRLF
+ N'    INSERT INTO #TablesWeDeleteFrom (SchemaName, TableName) VALUES ' + ISNULL(@TablesInsert, N'(N''dbo'',N''' + REPLACE(@EmployeeTable, N'''', N'''''') + N''')') + N';' + @CRLF
+ N'' + @CRLF
+ N'    PRINT N''Step 1: Bulk delete Security_GroupUsers (ALL FK columns, before loop)...'';' + @CRLF
+ N'    CREATE TABLE #EmpIds (ID BIGINT);' + @CRLF
+ N'    INSERT INTO #EmpIds SELECT se.ID FROM dbo.' + QUOTENAME(@EmployeeTable) + N' AS se WHERE se.LocalEmployeeID IN (''__NHAP_MA_NHAN_VIEN_VAO_DAY__'');' + @CRLF
+ N'    CREATE TABLE #FkCols (seq INT IDENTITY(1,1), Cs SYSNAME, Ct SYSNAME, Cc SYSNAME, Rs SYSNAME, Rt SYSNAME, Rk SYSNAME);' + @CRLF
+ N'    INSERT INTO #FkCols SELECT OBJECT_SCHEMA_NAME(fk.parent_object_id), OBJECT_NAME(fk.parent_object_id), CAST(COL_NAME(fkc.parent_object_id, fkc.parent_column_id) AS NVARCHAR(128)), OBJECT_SCHEMA_NAME(fk.referenced_object_id), OBJECT_NAME(fk.referenced_object_id), CAST(COL_NAME(fkc.referenced_object_id, fkc.referenced_column_id) AS NVARCHAR(128)) FROM sys.foreign_keys fk INNER JOIN sys.foreign_key_columns fkc ON fk.object_id = fkc.constraint_object_id WHERE fk.name LIKE N''FK_Security_GroupUsers_Security_Users%'' OR (OBJECT_NAME(fk.parent_object_id) = N''Security_GroupUsers'' AND OBJECT_NAME(fk.referenced_object_id) = N''Security_Users'');' + @CRLF
+ N'    SET @_i = 1;' + @CRLF
+ N'    SET @_max = (SELECT COUNT(*) FROM #FkCols);' + @CRLF
+ N'    WHILE @_i <= @_max' + @CRLF
+ N'    BEGIN' + @CRLF
+ N'        SELECT @_Cs = Cs, @_Ct = Ct, @_Cc = Cc, @_Rs = Rs, @_Rt = Rt, @_Rk = Rk FROM #FkCols WHERE seq = @_i;' + @CRLF
+ N'        SET @_Sql = N''DELETE FROM '' + QUOTENAME(@_Cs) + N''.'' + QUOTENAME(@_Ct) + N'' WHERE '' + QUOTENAME(@_Cc) + N'' IN (SELECT '' + QUOTENAME(@_Rk) + N'' FROM '' + QUOTENAME(@_Rs) + N''.'' + QUOTENAME(@_Rt) + N'' WHERE EmployeeID IN (SELECT ID FROM #EmpIds))'';' + @CRLF
+ N'        EXEC sp_executesql @_Sql;' + @CRLF
+ N'        PRINT N''  Column '' + ISNULL(@_Cc, N''?'') + N'' rows removed: '' + CAST(@@ROWCOUNT AS NVARCHAR(20));' + @CRLF
+ N'        SET @_i = @_i + 1;' + @CRLF
+ N'    END;' + @CRLF
+ N'    DROP TABLE #FkCols;' + @CRLF
+ N'    PRINT N''Step 1 done.'';' + @CRLF
+ N'    DROP TABLE #EmpIds;' + @CRLF
+ N'' + @CRLF
+ N'    OPEN mycur;' + @CRLF
+ N'    FETCH NEXT FROM mycur INTO @valEmployeeID;' + @CRLF
+ N'    WHILE @@FETCH_STATUS = 0' + @CRLF
+ N'    BEGIN' + @CRLF
+ N'        PRINT N''Processing EmployeeID: '' + CAST(@valEmployeeID AS NVARCHAR(20));' + @CRLF
+ N'        CREATE TABLE #FkCols2 (seq INT IDENTITY(1,1), Cs SYSNAME, Ct SYSNAME, Cc SYSNAME, Rs SYSNAME, Rt SYSNAME, Rk SYSNAME);' + @CRLF
+ N'        INSERT INTO #FkCols2 SELECT OBJECT_SCHEMA_NAME(fk.parent_object_id), OBJECT_NAME(fk.parent_object_id), CAST(COL_NAME(fkc.parent_object_id, fkc.parent_column_id) AS NVARCHAR(128)), OBJECT_SCHEMA_NAME(fk.referenced_object_id), OBJECT_NAME(fk.referenced_object_id), CAST(COL_NAME(fkc.referenced_object_id, fkc.referenced_column_id) AS NVARCHAR(128)) FROM sys.foreign_keys fk INNER JOIN sys.foreign_key_columns fkc ON fk.object_id = fkc.constraint_object_id WHERE fk.name LIKE N''FK_Security_GroupUsers_Security_Users%'' OR (OBJECT_NAME(fk.parent_object_id) = N''Security_GroupUsers'' AND OBJECT_NAME(fk.referenced_object_id) = N''Security_Users'');' + @CRLF
+ N'        SET @_i = 1;' + @CRLF
+ N'        SET @_max = (SELECT COUNT(*) FROM #FkCols2);' + @CRLF
+ N'        WHILE @_i <= @_max' + @CRLF
+ N'        BEGIN' + @CRLF
+ N'            SELECT @_Cs = Cs, @_Ct = Ct, @_Cc = Cc, @_Rs = Rs, @_Rt = Rt, @_Rk = Rk FROM #FkCols2 WHERE seq = @_i;' + @CRLF
+ N'            SET @_Sql = N''DELETE FROM '' + QUOTENAME(@_Cs) + N''.'' + QUOTENAME(@_Ct) + N'' WHERE '' + QUOTENAME(@_Cc) + N'' IN (SELECT '' + QUOTENAME(@_Rk) + N'' FROM '' + QUOTENAME(@_Rs) + N''.'' + QUOTENAME(@_Rt) + N'' WHERE EmployeeID = @valEmployeeID)'';' + @CRLF
+ N'            EXEC sp_executesql @_Sql, N''@valEmployeeID BIGINT'', @valEmployeeID = @valEmployeeID;' + @CRLF
+ N'            SET @_i = @_i + 1;' + @CRLF
+ N'        END;' + @CRLF
+ N'        DROP TABLE #FkCols2;' + @CRLF
+ N'' + @CRLF
+ N'        -- FK level 3, 2, 1 (child before parent)' + @CRLF
;

-- Cap 3 (neu co): bang -> bang -> bang -> Employee (xoa truoc cap 2)
DECLARE @Line NVARCHAR(MAX);
DECLARE @Cur CURSOR;

SET @Cur = CURSOR LOCAL FAST_FORWARD FOR
SELECT
    N'        DELETE FROM '
    + QUOTENAME(OBJECT_SCHEMA_NAME(fk3.parent_object_id)) + N'.' + QUOTENAME(OBJECT_NAME(fk3.parent_object_id))
    + N' WHERE '
    + QUOTENAME(CAST(COL_NAME(fkc3.parent_object_id, fkc3.parent_column_id) AS NVARCHAR(128)))
    + N' IN (SELECT '
    + QUOTENAME(CAST(COL_NAME(fkc3.referenced_object_id, fkc3.referenced_column_id) AS NVARCHAR(128)))
    + N' FROM '
    + QUOTENAME(OBJECT_SCHEMA_NAME(fk3.referenced_object_id)) + N'.' + QUOTENAME(OBJECT_NAME(fk3.referenced_object_id))
    + N' WHERE '
    + QUOTENAME(CAST(COL_NAME(fkc2.parent_object_id, fkc2.parent_column_id) AS NVARCHAR(128)))
    + N' IN (SELECT '
    + QUOTENAME(CAST(COL_NAME(fkc2.referenced_object_id, fkc2.referenced_column_id) AS NVARCHAR(128)))
    + N' FROM '
    + QUOTENAME(OBJECT_SCHEMA_NAME(fk2.referenced_object_id)) + N'.' + QUOTENAME(OBJECT_NAME(fk2.referenced_object_id))
    + N' WHERE '
    + QUOTENAME(CAST(COL_NAME(fkc1.parent_object_id, fkc1.parent_column_id) AS NVARCHAR(128)))
    + N' = @valEmployeeID));'
    + NCHAR(13) + NCHAR(10) + N'        PRINT N''  Deleted: '' + N''' + QUOTENAME(OBJECT_SCHEMA_NAME(fk3.parent_object_id)) + N'.' + QUOTENAME(OBJECT_NAME(fk3.parent_object_id)) + N''' + N'': '' + CAST(@@ROWCOUNT AS NVARCHAR(20)) + N'' row(s)'';'
FROM sys.foreign_keys AS fk1
INNER JOIN sys.foreign_key_columns AS fkc1 ON fk1.object_id = fkc1.constraint_object_id AND fk1.referenced_object_id = @EmployeeTableID
INNER JOIN sys.foreign_keys AS fk2 ON fk2.referenced_object_id = fk1.parent_object_id
INNER JOIN sys.foreign_key_columns AS fkc2 ON fk2.object_id = fkc2.constraint_object_id
INNER JOIN sys.foreign_keys AS fk3 ON fk3.referenced_object_id = fk2.parent_object_id
INNER JOIN sys.foreign_key_columns AS fkc3 ON fk3.object_id = fkc3.constraint_object_id
WHERE fk3.parent_object_id <> @EmployeeTableID
GROUP BY
    fk3.parent_object_id, fk3.referenced_object_id, fkc3.parent_object_id, fkc3.parent_column_id,
    fkc3.referenced_object_id, fkc3.referenced_column_id,
    fk2.referenced_object_id, fkc2.parent_object_id, fkc2.parent_column_id, fkc2.referenced_object_id, fkc2.referenced_column_id,
    fkc1.parent_object_id, fkc1.parent_column_id;

OPEN @Cur;
FETCH NEXT FROM @Cur INTO @Line;
WHILE @@FETCH_STATUS = 0 BEGIN SET @Script = @Script + @Line + @CRLF; FETCH NEXT FROM @Cur INTO @Line; END;
CLOSE @Cur; DEALLOCATE @Cur;

-- Cap 2: bang tham chieu bang con cua Employee (vd Security_GroupUsers -> Security_Users -> Employee)
SET @Cur = CURSOR LOCAL FAST_FORWARD FOR
SELECT
    N'        DELETE FROM '
    + QUOTENAME(OBJECT_SCHEMA_NAME(fk2.parent_object_id)) + N'.' + QUOTENAME(OBJECT_NAME(fk2.parent_object_id))
    + N' WHERE '
    + QUOTENAME(CAST(COL_NAME(fkc2.parent_object_id, fkc2.parent_column_id) AS NVARCHAR(128)))
    + N' IN (SELECT '
    + QUOTENAME(CAST(COL_NAME(fkc2.referenced_object_id, fkc2.referenced_column_id) AS NVARCHAR(128)))
    + N' FROM '
    + QUOTENAME(OBJECT_SCHEMA_NAME(fk2.referenced_object_id)) + N'.' + QUOTENAME(OBJECT_NAME(fk2.referenced_object_id))
    + N' WHERE '
    + QUOTENAME(CAST(COL_NAME(fkc1.parent_object_id, fkc1.parent_column_id) AS NVARCHAR(128)))
    + N' = @valEmployeeID);'
    + NCHAR(13) + NCHAR(10) + N'        PRINT N''  Deleted: '' + N''' + QUOTENAME(OBJECT_SCHEMA_NAME(fk2.parent_object_id)) + N'.' + QUOTENAME(OBJECT_NAME(fk2.parent_object_id)) + N''' + N'': '' + CAST(@@ROWCOUNT AS NVARCHAR(20)) + N'' row(s)'';'
FROM sys.foreign_keys AS fk1
INNER JOIN sys.foreign_key_columns AS fkc1
    ON fk1.object_id = fkc1.constraint_object_id AND fk1.referenced_object_id = @EmployeeTableID
INNER JOIN sys.foreign_keys AS fk2
    ON fk2.referenced_object_id = fk1.parent_object_id
INNER JOIN sys.foreign_key_columns AS fkc2
    ON fk2.object_id = fkc2.constraint_object_id
WHERE fk2.parent_object_id <> @EmployeeTableID
GROUP BY
    fk2.parent_object_id, fk2.referenced_object_id,
    fkc2.parent_object_id, fkc2.parent_column_id,
    fkc2.referenced_object_id, fkc2.referenced_column_id,
    fkc1.parent_object_id, fkc1.parent_column_id;

OPEN @Cur;
FETCH NEXT FROM @Cur INTO @Line;
WHILE @@FETCH_STATUS = 0
BEGIN
    SET @Script = @Script + @Line + @CRLF;
    FETCH NEXT FROM @Cur INTO @Line;
END;
CLOSE @Cur;
DEALLOCATE @Cur;

-- Cap 1: bang tham chieu truc tiep Staffing_Employees
SET @Cur = CURSOR LOCAL FAST_FORWARD FOR
SELECT
    N'        DELETE FROM '
    + QUOTENAME(OBJECT_SCHEMA_NAME(fk.parent_object_id)) + N'.' + QUOTENAME(OBJECT_NAME(fk.parent_object_id))
    + N' WHERE '
    + QUOTENAME(CAST(COL_NAME(fkc.parent_object_id, fkc.parent_column_id) AS NVARCHAR(128)))
    + N' = @valEmployeeID;'
    + NCHAR(13) + NCHAR(10) + N'        PRINT N''  Deleted: '' + N''' + QUOTENAME(OBJECT_SCHEMA_NAME(fk.parent_object_id)) + N'.' + QUOTENAME(OBJECT_NAME(fk.parent_object_id)) + N''' + N'': '' + CAST(@@ROWCOUNT AS NVARCHAR(20)) + N'' row(s)'';'
FROM sys.foreign_keys AS fk
INNER JOIN sys.foreign_key_columns AS fkc
    ON fk.object_id = fkc.constraint_object_id
WHERE fk.referenced_object_id = @EmployeeTableID
GROUP BY fk.parent_object_id, fkc.parent_object_id, fkc.parent_column_id;

OPEN @Cur;
FETCH NEXT FROM @Cur INTO @Line;
WHILE @@FETCH_STATUS = 0
BEGIN
    SET @Script = @Script + @Line + @CRLF;
    FETCH NEXT FROM @Cur INTO @Line;
END;
CLOSE @Cur;
DEALLOCATE @Cur;

-- Cuoi cung: xoa bang Employee (cha), dong vong lap cursor, Step 2/2b/3, END TRY / CATCH (moi dong 1 CRLF)
SET @Script = @Script + N'        DELETE FROM dbo.' + QUOTENAME(@EmployeeTable) + N' WHERE ID = @valEmployeeID;' + @CRLF
+ N'        PRINT N''  Deleted: dbo.'' + N''' + QUOTENAME(@EmployeeTable) + N''' + N'' (employee): '' + CAST(@@ROWCOUNT AS NVARCHAR(20)) + N'' row(s)'';' + @CRLF
+ N'        FETCH NEXT FROM mycur INTO @valEmployeeID;' + @CRLF
+ N'    END;' + @CRLF
+ N'' + @CRLF
+ N'    CLOSE mycur;' + @CRLF
+ N'    DEALLOCATE mycur;' + @CRLF
+ N'' + @CRLF
+ N'    PRINT N''Step 2: Check for orphans in Security_GroupUsers (before re-enable)...'';' + @CRLF
+ N'    SET @_Ct = NULL;' + @CRLF
+ N'    SELECT @_Cs = OBJECT_SCHEMA_NAME(fk.parent_object_id), @_Ct = OBJECT_NAME(fk.parent_object_id),' + @CRLF
+ N'           @_Cc = COL_NAME(fkc.parent_object_id, fkc.parent_column_id),' + @CRLF
+ N'           @_Rs = OBJECT_SCHEMA_NAME(fk.referenced_object_id), @_Rt = OBJECT_NAME(fk.referenced_object_id),' + @CRLF
+ N'           @_Rk = COL_NAME(fkc.referenced_object_id, fkc.referenced_column_id)' + @CRLF
+ N'    FROM sys.foreign_keys fk' + @CRLF
+ N'    INNER JOIN sys.foreign_key_columns fkc ON fk.object_id = fkc.constraint_object_id' + @CRLF
+ N'    WHERE fk.name LIKE N''FK_Security_GroupUsers_Security_Users%''' + @CRLF
+ N'       OR (OBJECT_NAME(fk.parent_object_id) = N''Security_GroupUsers'' AND OBJECT_NAME(fk.referenced_object_id) = N''Security_Users'');' + @CRLF
+ N'    IF @_Ct IS NOT NULL' + @CRLF
+ N'    BEGIN' + @CRLF
+ N'        SET @_Sql = N''SELECT @o = COUNT(*) FROM '' + QUOTENAME(@_Cs) + N''.'' + QUOTENAME(@_Ct) + N'' sg WHERE NOT EXISTS (SELECT 1 FROM '' + QUOTENAME(@_Rs) + N''.'' + QUOTENAME(@_Rt) + N'' su WHERE su.'' + QUOTENAME(@_Rk) + N'' = sg.'' + QUOTENAME(@_Cc) + N'')'';' + @CRLF
+ N'        EXEC sp_executesql @_Sql, N''@o INT OUTPUT'', @o = @_Orphan OUTPUT;' + @CRLF
+ N'        PRINT N''Security_GroupUsers orphan count (must be 0): '' + CAST(@_Orphan AS NVARCHAR(20));' + @CRLF
+ N'        IF @_Orphan > 0' + @CRLF
+ N'        BEGIN' + @CRLF
+ N'            CREATE TABLE #FkOrphans (seq INT IDENTITY(1,1), Cs SYSNAME, Ct SYSNAME, Cc SYSNAME, Rs SYSNAME, Rt SYSNAME, Rk SYSNAME);' + @CRLF
+ N'            INSERT INTO #FkOrphans SELECT OBJECT_SCHEMA_NAME(fk.parent_object_id), OBJECT_NAME(fk.parent_object_id), CAST(COL_NAME(fkc.parent_object_id, fkc.parent_column_id) AS NVARCHAR(128)), OBJECT_SCHEMA_NAME(fk.referenced_object_id), OBJECT_NAME(fk.referenced_object_id), CAST(COL_NAME(fkc.referenced_object_id, fkc.referenced_column_id) AS NVARCHAR(128)) FROM sys.foreign_keys fk INNER JOIN sys.foreign_key_columns fkc ON fk.object_id = fkc.constraint_object_id WHERE fk.name LIKE N''FK_Security_GroupUsers_Security_Users%'' OR (OBJECT_NAME(fk.parent_object_id) = N''Security_GroupUsers'' AND OBJECT_NAME(fk.referenced_object_id) = N''Security_Users'');' + @CRLF
+ N'            SET @_i = 1;' + @CRLF
+ N'            SET @_max = (SELECT COUNT(*) FROM #FkOrphans);' + @CRLF
+ N'            WHILE @_i <= @_max' + @CRLF
+ N'            BEGIN' + @CRLF
+ N'                SELECT @_Cs = Cs, @_Ct = Ct, @_Cc = Cc, @_Rs = Rs, @_Rt = Rt, @_Rk = Rk FROM #FkOrphans WHERE seq = @_i;' + @CRLF
+ N'                SET @_Sql = N''DELETE FROM '' + QUOTENAME(@_Cs) + N''.'' + QUOTENAME(@_Ct) + N'' WHERE '' + QUOTENAME(@_Cc) + N'' NOT IN (SELECT '' + QUOTENAME(@_Rk) + N'' FROM '' + QUOTENAME(@_Rs) + N''.'' + QUOTENAME(@_Rt) + N'')'';' + @CRLF
+ N'                EXEC sp_executesql @_Sql;' + @CRLF
+ N'                PRINT N''  Deleted orphans (FK col '' + ISNULL(@_Cc, N''?'') + N''): '' + CAST(@@ROWCOUNT AS NVARCHAR(20));' + @CRLF
+ N'                SET @_i = @_i + 1;' + @CRLF
+ N'            END;' + @CRLF
+ N'            DROP TABLE #FkOrphans;' + @CRLF
+ N'            PRINT N''Orphan rows removed. Proceeding to re-enable constraints.'';' + @CRLF
+ N'        END' + @CRLF
+ N'    END' + @CRLF
+ N'    PRINT N''Step 2b: Clean ALL FK orphans (repeat until no new orphans; xoa bang cha tao orphan moi o bang con)...'';' + @CRLF
+ N'    CREATE TABLE #AllFk (seq INT IDENTITY(1,1), Ps SYSNAME, Pt SYSNAME, Pc SYSNAME, Rs SYSNAME, Rt SYSNAME, Rk SYSNAME);' + @CRLF
+ N'    INSERT INTO #AllFk (Ps, Pt, Pc, Rs, Rt, Rk)' + @CRLF
+ N'    SELECT OBJECT_SCHEMA_NAME(fk.parent_object_id), OBJECT_NAME(fk.parent_object_id), CAST(COL_NAME(fkc.parent_object_id, fkc.parent_column_id) AS NVARCHAR(128)),' + @CRLF
+ N'           OBJECT_SCHEMA_NAME(fk.referenced_object_id), OBJECT_NAME(fk.referenced_object_id), CAST(COL_NAME(fkc.referenced_object_id, fkc.referenced_column_id) AS NVARCHAR(128))' + @CRLF
+ N'    FROM sys.foreign_keys fk' + @CRLF
+ N'    INNER JOIN sys.foreign_key_columns fkc ON fk.object_id = fkc.constraint_object_id' + @CRLF
+ N'    WHERE fk.referenced_object_id IN (SELECT OBJECT_ID(QUOTENAME(SchemaName) + N''.'' + QUOTENAME(TableName)) FROM #TablesWeDeleteFrom);' + @CRLF
+ N'    SET @_max = (SELECT COUNT(*) FROM #AllFk);' + @CRLF
+ N'    DECLARE @_Pass INT = 0, @_TotalRemoved INT = 1;' + @CRLF
+ N'    WHILE @_TotalRemoved > 0 AND @_Pass < 10' + @CRLF
+ N'    BEGIN' + @CRLF
+ N'        SET @_Pass = @_Pass + 1;' + @CRLF
+ N'        SET @_TotalRemoved = 0;' + @CRLF
+ N'        SET @_i = 1;' + @CRLF
+ N'        IF @_Pass > 1 PRINT N''  Step 2b pass '' + CAST(@_Pass AS NVARCHAR(5)) + N'' (xoa orphan moi phat sinh)...'';' + @CRLF
+ N'        WHILE @_i <= @_max' + @CRLF
+ N'        BEGIN' + @CRLF
+ N'            SELECT @_Cs = Ps, @_Ct = Pt, @_Cc = Pc, @_Rs = Rs, @_Rt = Rt, @_Rk = Rk FROM #AllFk WHERE seq = @_i;' + @CRLF
+ N'            SET @_Sql = N''DELETE FROM '' + QUOTENAME(@_Cs) + N''.'' + QUOTENAME(@_Ct) + N'' WHERE '' + QUOTENAME(@_Cc) + N'' IS NOT NULL AND '' + QUOTENAME(@_Cc) + N'' NOT IN (SELECT '' + QUOTENAME(@_Rk) + N'' FROM '' + QUOTENAME(@_Rs) + N''.'' + QUOTENAME(@_Rt) + N'' WHERE '' + QUOTENAME(@_Rk) + N'' IS NOT NULL)'';' + @CRLF
+ N'            BEGIN TRY' + @CRLF
+ N'                EXEC sp_executesql @_Sql;' + @CRLF
+ N'                SET @_Orphan = @@ROWCOUNT;' + @CRLF
+ N'                SET @_TotalRemoved = @_TotalRemoved + @_Orphan;' + @CRLF
+ N'                IF @_Orphan > 0' + @CRLF
+ N'                    PRINT N''  Orphans removed: '' + QUOTENAME(@_Ct) + N''.'' + QUOTENAME(@_Cc) + N'' (refs '' + QUOTENAME(@_Rt) + N''): '' + CAST(@_Orphan AS NVARCHAR(20)) + N'' row(s)'';' + @CRLF
+ N'                ELSE IF @_i % 50 = 0 AND @_Pass = 1' + @CRLF
+ N'                    PRINT N''  Step 2b: checked '' + CAST(@_i AS NVARCHAR(10)) + N'' / '' + CAST(@_max AS NVARCHAR(10)) + N'' FKs...'';' + @CRLF
+ N'            END TRY' + @CRLF
+ N'            BEGIN CATCH' + @CRLF
+ N'                PRINT N''  Skip (error): '' + QUOTENAME(@_Ct) + N''.'' + QUOTENAME(@_Cc) + N'': '' + ERROR_MESSAGE();' + @CRLF
+ N'            END CATCH' + @CRLF
+ N'            SET @_i = @_i + 1;' + @CRLF
+ N'        END;' + @CRLF
+ N'        IF @_TotalRemoved > 0 PRINT N''  Step 2b pass '' + CAST(@_Pass AS NVARCHAR(5)) + N'' total removed: '' + CAST(@_TotalRemoved AS NVARCHAR(20)) + N'' row(s).'';' + @CRLF
+ N'    END;' + @CRLF
+ N'    DROP TABLE #AllFk;' + @CRLF
+ N'    PRINT N''Step 2b done ('' + CAST(@_Pass AS NVARCHAR(5)) + N'' pass(es), '' + CAST(@_max AS NVARCHAR(10)) + N'' FKs per pass).'';' + @CRLF
+ N'    PRINT N''Step 3: Re-enabling constraints...'';' + @CRLF
+ N'    EXEC sp_MSforeachtable ''ALTER TABLE ? WITH CHECK CHECK CONSTRAINT ALL'';' + @CRLF
+ N'    EXEC sp_MSforeachtable ''ALTER TABLE ? ENABLE TRIGGER ALL'';' + @CRLF
+ N'' + @CRLF
+ N'    COMMIT TRANSACTION;' + @CRLF
+ N'    PRINT N''DeleteEmployee: Done. COMMIT.'';' + @CRLF
+ N'END TRY' + @CRLF
+ N'BEGIN CATCH' + @CRLF
+ N'    IF @@TRANCOUNT > 0 ROLLBACK TRANSACTION;' + @CRLF
+ N'    BEGIN TRY' + @CRLF
+ N'        EXEC sp_MSforeachtable ''ALTER TABLE ? WITH CHECK CHECK CONSTRAINT ALL'';' + @CRLF
+ N'        EXEC sp_MSforeachtable ''ALTER TABLE ? ENABLE TRIGGER ALL'';' + @CRLF
+ N'    END TRY BEGIN CATCH END CATCH;' + @CRLF
+ N'    DECLARE @ErrMsg NVARCHAR(4000) = ERROR_MESSAGE();' + @CRLF
+ N'    PRINT N''DeleteEmployee: Error - ROLLBACK. Message: '' + @ErrMsg;' + @CRLF
+ N'    THROW;' + @CRLF
+ N'END CATCH;' + @CRLF
;

-- Chuan hoa xuong dong thanh CRLF
SET @Script = REPLACE(REPLACE(REPLACE(@Script, NCHAR(13)+NCHAR(10), NCHAR(10)), NCHAR(13), NCHAR(10)), NCHAR(10), NCHAR(13)+NCHAR(10));

-- Phong truong hop export/paste lam dinh dong: sua lai cum "SET @_i = @_i" dinh "DELETE FROM" thanh dung cau truc
DECLARE @FixBlock NVARCHAR(500) = N'            SET @_i = @_i + 1;' + @CRLF + N'        END;' + @CRLF + N'        DROP TABLE #FkCols2;' + @CRLF + @CRLF + N'        -- FK level 3, 2, 1 (child before parent)' + @CRLF + N'        DELETE FROM';
SET @Script = REPLACE(@Script, N'            SET @_i = @_i        DELETE FROM', @FixBlock);
SET @Script = REPLACE(@Script, N'            SET @_i = @_i + DELETE FROM', @FixBlock);
SET @Script = REPLACE(@Script, N'            SET @_i = @_i + 1;        DELETE FROM', @FixBlock);

-- Tach thanh tung dong de xuat file (moi dong 1 row -> khi dung Results to File se co xuong dong dung)
DECLARE @Lines TABLE (Seq INT, Line NVARCHAR(MAX));
DECLARE @Pos INT = 1, @Next INT, @Len INT = LEN(@Script), @Seq INT = 0;

WHILE @Pos <= @Len
BEGIN
    SET @Next = CHARINDEX(NCHAR(13)+NCHAR(10), @Script + NCHAR(13)+NCHAR(10), @Pos);
    SET @Seq = @Seq + 1;
    INSERT INTO @Lines (Seq, Line) VALUES (@Seq, SUBSTRING(@Script, @Pos, @Next - @Pos));
    SET @Pos = @Next + 2;
END;

-- KET QUA: Tung dong script (UU TIEN dung "Results to File" de co file .sql dung xuong dong)
SELECT Line FROM @Lines ORDER BY Seq;

PRINT N'';
PRINT N'>>> CACH LAY SCRIPT (tranh comment het / dinh 1 dong):';
PRINT N'>>> 1. Query -> Results to File (hoac Ctrl+Shift+F), chon duong dan file .sql (vd DeleteEmployee.sql)';
PRINT N'>>> 2. Chay lai script nay (F5). File se duoc ghi voi moi dong script dung 1 dong.';
PRINT N'>>> 3. Mo file .sql, XOA DONG DAU TIEN (la ten cot "Line").';
PRINT N'>>> 4. Tim va thay __NHAP_MA_NHAN_VIEN_VAO_DAY__ bang ma nhan vien (vd 24449), roi chay file.';
